### ISSUE TITLE
Error in makeCNVcalls

### ISSUE THREAD

**Issue by cfrasier** [RahmanTeam/DECoN#24]
I can't seem to get the makeCNVcalls script to run properly. I changed the header names of the ExomeCount objects to reflect the update of the ExomeDepth package. However, I still seem to get the following error log.
```
Loading require```
d package: R.oo
Loading required package: R.methodsS3
R.methodsS3 v1.7.1 (2016-02-15) successfully loaded. See ?R.methodsS3 for help.
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
R.oo v1.22.0 (2018-04-21) successfully loaded. See ?R.oo for help.

Attaching package: ‘R.oo’

The following objects are masked from ‘package:methods’:

    getClasses, getMethods

The following objects are masked from ‘package:base’:

    attach, detach, gc, load, save

R.utils v2.9.0 successfully loaded. See ?R.utils for help.

Attaching package: ‘R.utils’

The following object is masked from ‘package:utils’:

    timestamp

The following objects are masked from ‘package:base’:

    cat, commandArgs, getOption, inherits, isOpen, nullfile, parse,
    warnings

[1] "BEGIN makeCNVCalls.R"
[1] "Processing sample: TN18-105679.recalreads.reheader 1/45"
Optimization of the choice of aggregate reference set, this process can take some time
Number of selected bins: 7021
Now fitting the beta-binomial model on a data frame with 8311 rows : this step can take a few minutes.
Now computing the likelihood for the different copy number states
Error in CallCNVs(x = all.exons, transition.probability = trans_prob,  : 
  Chromosome, start and end vector must have the same lengths.
Calls: CallCNVs -> CallCNVs
In addition: There were 22 warnings (use warnings() to see them)
Execution halted

```

Any help or fixes would be greatly appreciated.

**Comment by cfrasier** [comment]
I found the issue was with the 'names' option in the line where the error was occurring. It was the case of another ExomeCount header that had changed. Changing the header to match the version of the ExomeDepth package I had resolved the issue.

**Comment by diyang1354** [comment]
> I found the issue was with the 'names' option in the line where the error was occurring. It was the case of another ExomeCount header that had changed. Changing the header to match the version of the ExomeDepth package I had resolved the issue.

Hello,
I've encountered the same issue, could you please be more specific to what you changed? Thx.

**Comment by glbala87** [comment]
Hi cfrasier,

I've encountered the same issue, could you please be more specific to what you changed? Thank you.

**Comment by bugds** [comment]
> Hi cfrasier,
> 
> I've encountered the same issue, could you please be more specific to what you changed? Thank you.

> > I found the issue was with the 'names' option in the line where the error was occurring. It was the case of another ExomeCount header that had changed. Changing the header to match the version of the ExomeDepth package I had resolved the issue.
> 
> Hello, I've encountered the same issue, could you please be more specific to what you changed? Thx.

Hello all,
I changed the field name from "names" to "exon" and now everything seems to work.

Specifically, I changed this function call:
```
all.exons <- CallCNVs(
    x = all.exons,
    transition.probability = 10^-4,
    chromosome = counts$chromosome,
    start = counts$start,
    end = counts$end,
    name = counts$names # here
)
```
Now it looks like that:
```
all.exons <- CallCNVs(
    x = all.exons,
    transition.probability = 10^-4,
    chromosome = counts$chromosome,
    start = counts$start,
    end = counts$end,
    name = counts$exon # here
)
```
